[description]
skill_name = "WriterSkill.Acronym"
skill_description = "The skill is the ability to generate suitable acronym pairs for concepts, including obscure references."
output_name = "acronym_pair"
output_description = "A suitable acronym pair for the concept, consisting of an acronym and its expansion."
output_uses = "Can be used to quickly generate acronyms for concepts, including obscure references."
output_type = "text/string"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The concept for which an acronym pair should be generated."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

