[description]
skill_name = "QASkill.Question"
skill_description = "The skill is the ability to answer questions based on a given set of information."
output_name = "answer"
output_description = "The answer to the given question."
output_uses = "Can be used to provide answers to questions posed to an AI assistant."
output_type = "text/string"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The question posed to the AI assistant."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

