[description]
skill_name = "QASkill.AssistantResults"
skill_description = "The skill is the ability to use the results from an API call to answer a query."
output_name = "answer"
output_description = "The answer to the query based on the results from the API call."
output_uses = "Can be used to answer questions based on the results of an API call."
output_type = "text/string"
[[description.arguments]]
argument_name = "api"
argument_identifier = "{{$api}}"
argument_description = "The API call to be made."
argument_sources = "Specified by the user or inferred from the context."
argument_type = "text/string"

[[description.arguments]]
argument_name = "results"
argument_identifier = "{{$results}}"
argument_description = "The results from the API call."
argument_sources = "The results of the API call."
argument_type = "text/string"

[[description.arguments]]
argument_name = "resultsContext"
argument_identifier = "{{$resultsContext}}"
argument_description = "The context of the results from the API call."
argument_sources = "The context of the results of the API call."
argument_type = "text/string"

[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The query to be answered using the results from the API call."
argument_sources = "Specified by the user or inferred from the context."
argument_type = "text/string"

