[description]
skill_name = "CalendarSkill.AssistantShowCalendarEvents"
skill_description = "The skill is the ability to generate a list of calendar events within a specified time frame."
output_name = "calendar_events"
output_description = "A list of calendar events within the specified time frame."
output_uses = "Can be used to answer questions about events within a certain time frame."
output_type = "application/json"
[[description.arguments]]
argument_name = "context"
argument_identifier = "{{$context}}"
argument_description = "The context of the query, such as the type of events to be listed."
argument_sources = "Provided by the user or inferred from conversation/dialogue."
argument_type = "text/string"

[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The time frame for which the events should be listed."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

