[description]
skill_name = "WriterSkill.TranslateV2"
skill_description = "The skill is the ability to detect the language of a given text, translate it to English, and improve the text by replacing simplified words and sentences with more elegant and literary words and sentences."
output_name = "translation"
output_description = "The translated and improved version of the text in English."
output_uses = "Can be used to quickly and accurately translate and improve text in any language to English."
output_type = "text/string"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The text to be translated and improved."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

