[description]
skill_name = "WriterSkill.Rewrite"
skill_description = "The skill is the ability to rewrite text in a given style while retaining the original meaning and factual content."
output_name = "rewritten_text"
output_description = "The rewritten text in the given style while retaining the original meaning and factual content."
output_uses = "Can be used to rewrite text in a given style while preserving the original meaning and factual content."
output_type = "text/string"
[[description.arguments]]
argument_name = "style"
argument_identifier = "{{$style}}"
argument_description = "The style in which the text should be rewritten."
argument_sources = "Specified by the user or inferred from the context."
argument_type = "text/string"

[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The original text to be rewritten."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

