[description]
skill_name = "MiscSkill.Continue"
skill_description = "The skill is an empty template meant to allow the continuation of a prompt response from an AI."
output_name = "continuation"
output_description = "The continuation of the prompt response."
output_uses = "Can be used to continuously allow the AI make longer responses."
output_type = "application/json"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The input to be continued."
argument_sources = "The input should come from a previous skill output or loaded from historical data."
argument_type = "text/string"

