[description]
skill_name = "CodingSkill.CommandLinePython"
skill_description = "The skill is the ability to write a Python 3.x command line script with a single function, using sys.argv and sys.stdin, and handling errors with explanations as comments."
output_name = "python_script"
output_description = "A fully executable Python 3.x command line script."
output_uses = "To perform actions, retrieve information, or generate results based on the instructions given in the script on a Python 3.x host."
output_type = "text/python"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The instructions for the Python script to accomplish."
argument_sources = "A list of instructions, commands, or descriptions about a task that can be converted into a Python script."
argument_type = "text/string"

