[description]
skill_name = "CodingSkill.DevelopmentSupport"
skill_description = "The skill is the ability to provide a step-by-step solution to a problem based on the provided information."
output_name = "solution"
output_description = "A step-by-step solution to the problem."
output_uses = "Can be used by developers to quickly solve problems and understand the steps needed to do so."
output_type = "text/string"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The problem that needs to be solved."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

