[description]
skill_name = "ChildrensBookSkill.BookIdeas"
skill_description = "The skill is the ability to generate a list of ideas for a children's book based on a given topic."
output_name = "ideas"
output_description = "A list of ideas for a children's book, represented as a valid json string, as an array of [{ \"title\": \"the title\", \"description\":\"the short description\" }]."
output_uses = "Can be used to generate ideas for a children's book quickly and easily."
output_type = "application/json"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The topic to generate ideas for the children's book."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

[[description.arguments]]
argument_name = "numIdeas"
argument_identifier = "{{$numIdeas}}"
argument_description = "The number of ideas to generate."
argument_sources = "Specified by the user or inferred from the context."
argument_type = "number/integer"

