[description]
skill_name = "SelfRefine.DescribeSkill"
skill_description = "The skill of providing concise and accurate descriptions for prompt templates used in generating tasks and scenarios for an AI chatbot."
output_name = "skill_description"
output_description = "A string that is fully compliant with the TOML format whose structure is exactly like this file."
output_uses = "These descriptions are used to help the AI chatbot understand the purpose of the prompt template."
output_type = "text/toml"

[[description.arguments]]
argument_name = "prompt_template"
argument_description = "The template format used for generating tasks and scenarios."
argument_identifier = "{{$undescribed_template}}"
argument_sources = "The prompt templates used in completing the tasks and scenarios found in the skill repository."
argument_type = "text/string"