[description]
skill_name = "WriterSkill.TwoSentenceSummary"
skill_description = "The skill is the ability to summarize a given text into two sentences or less."
output_name = "summary"
output_description = "A summary of the given text in two sentences or less."
output_uses = "Can be used to quickly summarize large amounts of text."
output_type = "text/string"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The text to be summarized."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

