[description]
skill_name = "SummarizeSkill.Summarize"
skill_description = "The skill is the ability to generate a concise summary of a given text, following a set of rules and avoiding certain phrases."
output_name = "summary"
output_description = "A concise summary of the given text."
output_uses = "Can be used to quickly summarize a text for easier understanding or to save time."
output_type = "text/string"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The text to be summarized."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

