[description]
skill_name = "QASkill.ContextQuery"
skill_description = "The skill allows the AI assistant to generate well-formed XML tags based on the provided instructions and context."
output_name = "xml_code"
output_description = "A fully executable XML tag."
output_uses = "To perform actions, retrieve information, or generate results based on the instructions given in the XML tag."
output_type = "text/string"
[[description.arguments]]
argument_name = "time"
argument_identifier = "{{time}}"
argument_description = "The current date and time."
argument_sources = "The system's clock or a user provided date and time."
argument_type = "text/string"

[[description.arguments]]
argument_name = "firstname"
argument_identifier = "{{$firstname}}"
argument_description = "The first name or identifier of the user interacting with the AI assistant."
argument_sources = "The user's first name can be directly provided, inferred from previous interactions, or obtained from a user profile."
argument_type = "text/string"

[[description.arguments]]
argument_name = "lastname"
argument_identifier = "{{$lastname}}"
argument_description = "The last name or identifier of the user interacting with the AI assistant."
argument_sources = "The user's last name can be directly provided, inferred from previous interactions, or obtained from a user profile."
argument_type = "text/string"

[[description.arguments]]
argument_name = "city"
argument_identifier = "{{$city}}"
argument_description = "The city or location of the user interacting with the AI assistant."
argument_sources = "The user's city can be directly provided, inferred from previous interactions, or obtained from a user profile."
argument_type = "text/string"

[[description.arguments]]
argument_name = "state"
argument_identifier = "{{$state}}"
argument_description = "The state or region of the user interacting with the AI assistant."
argument_sources = "The user's state can be directly provided, inferred from previous interactions, or obtained from a user profile."
argument_type = "text/string"

[[description.arguments]]
argument_name = "country"
argument_identifier = "{{$country}}"
argument_description = "The country of the user interacting with the AI assistant."
argument_sources = "The user's country can be directly provided, inferred from previous interactions, or obtained from a user profile."
argument_type = "text/string"

[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The description of a task the XML tag must accomplish."
argument_sources = "A list of instructions, commands, or descriptions about a task that can be converted into an XML tag."
argument_type = "text/xml"

