[description]
skill_name = "WriterSkill.ShortPoem"
skill_description = "The skill is the ability to generate a humorous poem or limerick based on a given event."
output_name = "poem"
output_description = "A humorous poem or limerick generated based on the given event."
output_uses = "Can be used to provide a humorous take on a given event or topic."
output_type = "text/string"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The event or topic for which the poem should be generated."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

