[description]
skill_name = "CodingSkill.DOSScript"
skill_description = "The skill allows the AI assistant to create executable DOS scripts that can perform specific actions based on the provided instructions."
output_name = "dos_code"
output_description = "A fully executable dos script."
output_uses = "To perform actions, retrieve information, or generate results based on the instructions given in the script on a windows based host."
output_type = "text/string"
[[description.arguments]]
argument_name = "firstName"
argument_identifier = "{{$firstName}}"
argument_description = "The first name or identifier of the user interacting with the AI assistant."
argument_sources = "The user's first name can be directly provided, inferred from previous interactions, or obtained from a user profile."
argument_type = "text/string"

[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The description of a task the DOS script must accomplish."
argument_sources = "A list of instructions, commands, or descriptions about a task that can be converted into a DOS script."
argument_type = "text/string"

