[description]
skill_name = "Standard.SingleInput"
skill_description = "The skill allows the AI assistant to generate jokes based on a given topic and style."
output_name = "joke"
output_description = "A humorous story or joke based on the given topic and style."
output_uses = "Can be used to provide entertainment or to lighten the mood in conversations."
output_type = "text/string"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The topic and style of the joke to be generated."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"