[description]
skill_name = "WriterSkill.TellMeMore"
skill_description = "The skill is the ability to generate a verbose and detailed overview of a conversation, focusing on a specific area."
output_name = "overview"
output_description = "A verbose and detailed overview of a conversation, focusing on a specific area."
output_uses = "Can be used to provide a comprehensive overview of a conversation for further analysis or review."
output_type = "text/string"
[[description.arguments]]
argument_name = "conversationtype"
argument_identifier = "{{$conversationtype}}"
argument_description = "The type of conversation the overview is based on."
argument_sources = "Specified by the user or inferred from the context."
argument_type = "text/string"

[[description.arguments]]
argument_name = "focusarea"
argument_identifier = "{{$focusarea}}"
argument_description = "The specific area of the conversation to focus on in the overview."
argument_sources = "Specified by the user or inferred from the context."
argument_type = "text/string"

[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The conversation to be summarized."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

[[description.arguments]]
argument_name = "previousresults"
argument_identifier = "{{$previousresults}}"
argument_description = "The overview of the previous part of the conversation, focusing on the specified area."
argument_sources = "Generated by the AI assistant."
argument_type = "text/string"

