[description]
skill_name = "Standard.MultipleInputs"
skill_description = "The skill allows the AI assistant to generate emails based on the provided instructions."
output_name = "email"
output_description = "A fully composed email based on the user's instructions."
output_uses = "To communicate with other people, provide reminders, or generate results based on the instructions given in the email."
output_type = "text/string"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The instructions for the email, including the recipient, purpose, and any relevant information."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

[[description.arguments]]
argument_name = "date"
argument_identifier = "{{$date}}"
argument_description = "The date the email is being sent."
argument_sources = "The current date or a date specified by the user."
argument_type = "text/string"

[[description.arguments]]
argument_name = "name"
argument_identifier = "{{$name}}"
argument_description = "The name of the sender of the email."
argument_sources = "The user's name can be directly provided, inferred from previous interactions, or obtained from a user profile."
argument_type = "text/string"

