[description]
skill_name = "CodingSkill.Entity"
skill_description = "The skill is the ability to inject xml tags into a given text for formatting and rendering effects."
output_name = "processed_text"
output_description = "The original text with the xml tags injected inline."
output_uses = "Can be used to add additional information to a text, such as formatting, styling, or other tags."
output_type = "text/xml"
[[description.arguments]]
argument_name = "tags"
argument_identifier = "{{$tags}}"
argument_description = "The xml tags to be injected into the text."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/xml"

[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The original text to be processed."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

