[description]
skill_name = "WriterSkill.Brainstorm"
skill_description = "The skill is the ability to generate a numbered list of ideas based on a given topic."
output_name = "ideas"
output_description = "A numbered list of ideas based on the given topic."
output_uses = "Can be used to generate ideas for a project, brainstorm solutions to a problem, or create a list of items to be used in a task."
output_type = "text/string"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$INPUT}}"
argument_description = "The topic or prompt for the list."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

