[description]
skill_name = "FunSkill.Limerick"
skill_description = "The skill is the ability to generate a humorous limerick based on a given name and invented facts about their life."
output_name = "limerick"
output_description = "A humorous limerick based on the given name and invented facts about their life."
output_uses = "Can be used to entertain or amuse people with a funny limerick."
output_type = "text/string"
[[description.arguments]]
argument_name = "name"
argument_identifier = "{{$name}}"
argument_description = "The name of the person the limerick is about."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "Request or instructions about how to generate the limerick."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"