[description]
skill_name = "SummarizeSkill.Topics"
skill_description = "The skill is the ability to extract key topics from a given text."
output_name = "topics"
output_description = "A list of topics extracted from the given text."
output_uses = "Can be used to quickly summarize a text and identify key topics."
output_type = "application/xml"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The text from which topics should be extracted."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

