[description]
skill_name = "SummarizeSkill.Topics"
skill_description = "The skill is the ability to extract key topics from a given text."
output_name = "topics"
output_description = "A list of topics extracted from the given text."
output_uses = "Can be used to quickly summarize large amounts of text into a few key topics or pieces of information for reference."
output_type = "application/xml"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The text or content from which topics should be extracted."
argument_sources = "Provided by the user, pulled from a database, taken from a file, scraped from a website, compiled from other skills, etc."
argument_type = "text/string"

