[description]
skill_name = "QASkill.Form"
skill_description = "The skill is the ability to respond to user input using XML tags, providing a well-formed XML response."
output_name = "xml_response"
output_description = "A well-formed XML response based on the user's input."
output_uses = "Can be used to provide a structured response to user input in a conversation."
output_type = "application/xml"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The user's input that needs to be responded to."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

[[description.arguments]]
argument_name = "promptName"
argument_identifier = "{{$promptName}}"
argument_description = "The name of the prompt that is being responded to."
argument_sources = "Specified by the user or inferred from the context."
argument_type = "text/string"

