[description]
skill_name = "WriterSkill.StoryGen"
skill_description = "The skill is the ability to format text into well-formed XML, using only the specified tags, and to wrap code in CDATA tags."
output_name = "formatted_xml"
output_description = "Well-formed XML with the specified tags and code wrapped in CDATA tags."
output_uses = "Can be used to generate XML documents with specific tags and code."
output_type = "application/xml"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The text to be formatted into XML."
argument_sources = "Provided by the user or extracted from conversation/dialogue."
argument_type = "text/string"

[[description.arguments]]
argument_name = "xml_tags"
argument_identifier = "{{$xml_tags}}"
argument_description = "The list of XML tags to be used in the formatting."
argument_sources = "Specified by the user or inferred from the context."
argument_type = "list/string"

