[description]
skill_name = "SummarizeSkill.Notegen"
skill_description = "The skill is the ability to extract key points from a given text and store them in a memory for later use."
output_name = "memory"
output_description = "A collection of key points extracted from the given text."
output_uses = "Can be used to analyze the rest of the document, for other relevant tasks, or stored as a memory for later use."
output_type = "text/list"
[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The text or content from which key points should be extracted."
argument_sources = "Provided by the user, extracted from a document, retrieved from a database, or provided by another skill."
argument_type = "text/string"

